name: Writeups
description: Syncing

inputs:
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout writeups repository
      uses: actions/checkout@v4
      with:
        repository: GerlachSnezka/writeups
        token: ${{ inputs.token }}
        path: out

    - run: |
        cd out/
        ./update.sh
      shell: bash

    - name: Commit and push
      run: |
        cd out/
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update writeups"
        git push
