name: Sync website
on:
  push:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: GerlachSnezka/gerlachsnezka.github.io
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true
          path: out

      - name: Commit and push
        working-directory: out
        run: |
          ./make.sh
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update writeups 🚀"
          git push
